default: &default
  host: ruby.rodionov.webtm.ru
  adapter: postgresql
  encoding: UTF8
  username: ruby_app
  timeout: 5000
  reaping_frequency: 30
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rubyonov_development
  password: <%= Rails.application.credentials.database[:password] %>

test:
  <<: *default
  database: rubyonov_test
  password: <%= Rails.application.credentials.database[:password] %>

production:
  <<: *default
  database: rubyonov_production
  password: <%= ENV['EXERCISE_DATABASE_PASSWORD'] %>
